import { Geist, Geist_Mono } from "next/font/google";
import Link from "next/link";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Data Analysis System",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        
        {/* Global Navigation */}
        <nav style={{ 
          padding: "16px", 
          display: "flex", 
          gap: "1rem", 
          borderBottom: "1px solid #e2e8f0" 
        }}>
          <Link href="/">Home</Link>
          <Link href="/pagetwo">Data Preview Page</Link>
        </nav>

        {/* Page Content */}
        <main style={{ padding: "20px" }}>
          {children}
        </main>
      </body>
    </html>
  );
}